export const rawMale =
  `Robbie Arms
Howard Kimrey
Luke Grissett
Sterling Saraiva
Trey Stahly
Guillermo Jones
Winford Sartori
Efrain Frei
Delmer Zimmerer
Jamal Stowell
Ali Mcglaughlin
Kirk Considine
Devon Bjork
Huey Lui
Kelley Carlisle
Sydney Symes
Theo Nida
Jose Debartolo
Stuart Chevere
Oswaldo Yamada
Reynaldo Couey
Donny Benoit
Wm Madera
Elton Servin
Issac Pestana
Jay Kizer
Titus Monsour
Korey Murphey
Brad Blasi
Raul Roper
Chang Valenta
Numbers Poyner
Ross Marciano
Ulysses Higgenbotham
Dana Rousseau
Jospeh Furst
Evan Veatch
Markus Tuohy
Stevie Dawn
Marc Belanger
Charley Schoonmaker
Scottie Partington
Sherwood Reichert
Colin Denardo
Santiago Webber
Corey Luce
Jordon Leiker
Pasquale Klima
Delmar Partain
Mack Valtierra`

export const rawFemale =
  `Shan Westerberg
Karina Ostroff
Cindy Primus
Veronica Riggio
Coletta Raine
Calista Hagedorn
Keitha Lanman
Lea Averill
Tomoko Valentino
Jonna Rebello
Toshiko Neveu
Jama Chamblee
Rosaria Sallee
Janell Cannella
Flor Comfort
Cherilyn Ruggerio
Kerrie Strasser
Ashely Greenhill
Kesha Addario
Alysha Duhe
Vada Berkey
Tamara Guillemette
Lanora Stoops
Terisa Ballerini
Rossana Puchalski
Karena Hanneman
Bibi Blanc
Shenika Cruzado
Bette Pippenger
Antionette Gibby
Lissette Preston
Delsie Charters
Ji Braham
Delfina Bosco
Renate Roundy
Rosanna Cocke
Yolonda Diedrich
Macie Bruning
Tyisha Warf
Shanti Corby
Vi Kucera
Dennise Hippler
Siobhan Haris
Marlys Dales
Christy Steen
Burma Ladson
Sari Fort
Jaquelyn Kingsley
Leanna Beckles
Jeanelle Fortner  `
